INSERT INTO `shop` (name, location)
VALUES ('Pura Vida', 'Koh Tao, Thailand'),
('Apo Divers', 'Siquijor, Philippines'),
('Zen Diver', 'Bali, Indonesia'),
('Blue Dive', 'Costa Rica'),
('Blue Label Diving', 'Phuket, Thailand'),
('Thai Dive Center', 'Nonthaburi, Thailand'),
('Seamonkey', 'Selangor, Malaysia'),
('Dive Downbelow', 'Sabah, Malaysia'),
('Sea Rider', 'Puerto Galera, Philippines'),
('Tarvis Dive', 'Palawan, Philippines'),
('Spice Island', 'Maluku, Indonesia'),
('Dive Komodo', 'Nusa Tenggara, Indonesia');

INSERT INTO `shop_language` (`shop_id`, `language_id`)
VALUES ('2', '1'),
('2', '7'),
('2', '3'),
('4', '1'),
('4', '8'),
('1', '1'),
('1', '2'),
('3', '12'),
('3', '1'),
('5', '17'),
('5', '18'),
('11', '3'),
('11', '9'),
('10', '1'), 
('6', '8'),
('6', '6'),
('12', '12'),
('12', '1'),
('8', '1'),
('7', '4'),
('9', '5'),
('9', '10');